version: "3.4"

x-restart-policy: &restart_policy
  restart: unless-stopped
x-logging-config: &logging_config
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "50m"

#volumes:
#  postgres:

services:
  nextcloud-dev:
    <<: [*restart_policy, *logging_config]
    image: ghcr.io/juliusknorr/nextcloud-dev-php84:latest
    ports:
      - 8080:80
    volumes:
      - ${PWD}/../:/var/www/html/apps-extra/timemanager:ro
    environment:
      SERVER_BRANCH: ${SERVER_BRANCH}
#      SQL: ${SQL:-mysql}
#    depends_on:
#      - database-pgsql

#  database-pgsql:
#    image: postgres:latest
#    environment:
#      POSTGRES_DB: nextcloud
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "${IP_BIND:-127.0.0.1}:${PORTBASE:-800}2:5432"
#    volumes:
#      - postgres:/var/lib/postgresql

#
# Useful commands:
# - docker-compose up
# - docker-compose down -v
# - rm -rf /tmp/server
# Create an .env file with version:
# - SERVER_BRANCH=v28.0.0rc2

