<?php

return [
	"routes" => [
		["name" => "page#index", "url" => "/", "verb" => "GET"],
		["name" => "page#reports", "url" => "/reports", "verb" => "GET"],
		["name" => "page#clients", "url" => "/clients", "verb" => "GET"],
		["name" => "page#addClient", "url" => "/clients", "verb" => "POST"],
		["name" => "page#editClient", "url" => "/clients", "verb" => "PATCH"],
		["name" => "page#deleteClient", "url" => "/clients/delete", "verb" => "POST"],
		["name" => "page#projects", "url" => "/projects", "verb" => "GET"],
		["name" => "page#addProject", "url" => "/projects", "verb" => "POST"],
		["name" => "page#editProject", "url" => "/projects", "verb" => "PATCH"],
		["name" => "page#deleteProject", "url" => "/projects/delete", "verb" => "POST"],
		["name" => "page#tasks", "url" => "/tasks", "verb" => "GET"],
		["name" => "page#addTask", "url" => "/tasks", "verb" => "POST"],
		["name" => "page#editTask", "url" => "/tasks", "verb" => "PATCH"],
		["name" => "page#deleteTask", "url" => "/tasks/delete", "verb" => "POST"],
		["name" => "page#times", "url" => "/times", "verb" => "GET"],
		["name" => "page#addTime", "url" => "/times", "verb" => "POST"],
		["name" => "page#editTime", "url" => "/times", "verb" => "PATCH"],
		["name" => "page#deleteTime", "url" => "/times/delete", "verb" => "POST"],
		["name" => "page#payTime", "url" => "/times/paid", "verb" => "POST"],
		["name" => "page#unpayTime", "url" => "/times/unpaid", "verb" => "POST"],
		["name" => "page#updateSettings", "url" => "/settings", "verb" => "POST"],
		["name" => "page#tools", "url" => "/tools", "verb" => "GET"],
		["name" => "t_api#get", "url" => "/api/items", "verb" => "GET"],
		["name" => "t_api#post", "url" => "/api/items", "verb" => "POST"],
		["name" => "t_api#updateObjects", "url" => "/api/updateObjects", "verb" => "POST"],
		["name" => "t_api#updateObjectsFromWeb", "url" => "/api/sync-web", "verb" => "POST"],
		["name" => "t_api#getHoursInPeriodStats", "url" => "/api/hoursInPeriod", "verb" => "GET"],
	],
];
